################
# YAML anchors #
################
opendoor_yaml_definitions: 
  access_token_additional: &access_token_additional
    - ((github-token-from-app-1))
    - ((github-token-from-app-2))
    - ((github-token-from-app-3))
    - ((github-token-from-app-4))
    - ((github-token-from-app-5))
    - ((github-token-from-app-6))
    - ((github-token-from-app-7))
    - ((github-token-from-app-8))
    - ((github-token-from-app-9))
    - ((github-token-from-app-10))
  image_resource: &dev-tools
    name: ""
    source:
      password: ((dockerhub-password))
      repository: opendoor/dev-tools
      username: ((dockerhub-username))
    type: docker-image

####################
## Resource Types ##
####################
resource_types:
  - name: od-pull-request
    type: docker-image
    source:     
      repository: opendoor/telia-oss-github-pr-resource
      # stored in vault concourse/shared
      # most likely 'dev' if you are doing a code review ;)
      tag: ((od-github-pr-resource-tag))

###############
## Resources ##
###############
resources:
  - name: pr-branch
    type: od-pull-request
    source:
      access_token: ((github-token))
      access_token_additional: *access_token_additional
      # for testing purposes ... realistically, we should never set min_remaining_threshold_before_using_access_token_additional
      # and use the default defined in git.go
      min_remaining_threshold_before_using_access_token_additional : 20000
      # WIP metrics ... placeholder for now
      datadog_api_key: ((datadog-api-key))
      datadog_app_key: ((datadog-app-key))
      base_branch: master
      repository: opendoor-labs/code

##########
## Jobs ##
##########
jobs:
  - name: sample-opendoor-github-pr-resource
    # run multiple jobs in parallel
    serial: false
    plan:
      - get: pr-branch
        trigger: true
        # I changed the code for version: latest
        # this feature isn't commented very well
        version: every
      - config:
          image_resource: *dev-tools
          inputs:
          - name: pr-branch
          platform: linux
          run:
            args:
            - -c
            - |-
              echo "Hello World"
              pwd
              ls -l
              ls -l pr-branch
            path: bash
        task: list-files  
  
